GET http://localhost:8080/url-shortener

###
GET http://localhost:8080/url-shortener

https://shrt.fr/097aio

### why does it work? json is implicly converted
POST http://localhost:8080/url-shortener
Content-Type: application/json

{ "urlToShorten": "https://www.google.com" }
###
POST http://localhost:8080/url-shortener

###
POST http://localhost:8080/url-shortener
Content-Type: text/plain

https://www.google.com

###
GET http://localhost:8080/url-shortener/all-shorten-urls
