package com.centralpaytest.urlshortener.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static java.util.stream.Collectors.toList;

@Service
public class ShortenerService {
    final String URL_STARTER = "https://shrt.fr/";
    Map<Integer, String> IDS_TO_RETRIEVE_URL = new HashMap<>(); // TODO replace by database
    StringEncoder stringEncoder;

    @Autowired
    ShortenerService(StringEncoder stringEncoder) {
        this.stringEncoder = stringEncoder;
        IDS_TO_RETRIEVE_URL.put(Math.abs(URL_STARTER.hashCode()), URL_STARTER);  // hashCode can return a negative number due to int limit
    }

    /**
     * @param longUrl url to shorten
     * @return a string representing the input as a shorter string
     */
    public String shortenUrl(String longUrl) throws Exception {
        // hashCode can return a negative number due to int limit
        int idUrl = Math.abs(longUrl.hashCode()); // TODO better will be with unique database ID
        if (IDS_TO_RETRIEVE_URL.get(idUrl) == null) {
            IDS_TO_RETRIEVE_URL.put(idUrl, longUrl);
        } else {
            throw new Exception("Impossible to shorten this URL");
        }
        return URL_STARTER.concat(stringEncoder.encode(idUrl));
    }

    public String getOriginalUrlFrom(String shortUrl) throws Exception {
        if (!shortUrl.startsWith(URL_STARTER)) {
            throw new Exception("The given URL was not generated by this service");
        }
        String toDecode = shortUrl.substring(URL_STARTER.length());
        int id = stringEncoder.decode(toDecode);
        return IDS_TO_RETRIEVE_URL.get(id);
    }

    /**
     * @param url a url without any path (protocol + sub domain + domains)
     * @return list of generated shorten url related to
     */
    public List<String> getShortenUrlsFromBase(String url) {
        String toSearch = url != null && url.endsWith("/") ? url.substring(0, url.length() - 1) : url;
        List<Integer> idsToEncode = IDS_TO_RETRIEVE_URL.entrySet().stream()
                .filter(entry -> entry.getValue().startsWith(toSearch))
                .map(Map.Entry::getKey)
                .collect(toList());
        return idsToEncode.stream().map(id -> URL_STARTER.concat(stringEncoder.encode(id))).collect(toList());
    }
}
